/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function imageToWebp(path: string, distPath: string): boolean
export function webImageToWebp(url: string, distPath: string): boolean
export function findAllUrl(path: string): Array<string>
